/* Copyright (C) 2026 Tom Frischmuth — GPLv3. Modified by Yosef, 2026. */

package com.dalelalmuslim.knote.ui.screens

internal const val TIP_INTERVAL_MS = 60_000L

internal val TIPS_AR = listOf(
    "تنفّس بهدوء لأربع عدّات، ثم أخرج النفس ببطء لست عدّات.",
    "عندما يتشتت الذهن، عُد بلطف إلى التنفس من دون إصدار أحكام.",
    "لا تحاول تغيير شيء؛ راقب ما يحدث كما هو.",
    "تفقّد جسدك من الداخل: القدمين والساقين والبطن والصدر واليدين.",
    "دع كل فكرة تمر مثل سحابة تعبر السماء.",
    "وجّه انتباهك إلى الوقفة الطبيعية بين الشهيق والزفير.",
    "عندما تظهر الأصوات، لاحظها من دون تصنيف أو حكم.",
    "أنت المراقب، ولست الشيء الذي تتم مراقبته.",
    "مع كل زفير، اسمح لنفسك بأن تترك شيئًا من التوتر.",
    "أرخِ جبهتك وفكّك وكتفيك ويديك بوعي.",
    "اشعر بنقاط تماس جسدك مع الأرض أو المقعد.",
    "تخيّل أن قلبك يتنفس بلطف وبإيقاع هادئ.",
    "ابتسامة داخلية رقيقة تساعد الجسد كله على الاسترخاء.",
    "هذه اللحظة مكتملة، ولا ينقصها شيء.",
    "عدّ عشرة أنفاس بصمت، ثم ابدأ من جديد.",
    "لاحظ الموضع الذي تشعر فيه بالتنفس بأوضح صورة.",
    "أرسل لنفسك أمنية بالراحة: لعلني أكون سعيدًا ومطمئنًا.",
    "وسّعها إلى الآخرين: لعل جميع الكائنات تكون سعيدة وخالية من المعاناة.",
    "عند القلق، تنفّس بعمق نحو البطن؛ فهذا يساعد الجهاز العصبي على الهدوء.",
    "تخيّل ذهنك بحيرة ساكنة؛ الأفكار أمواج تظهر ثم تنحسر.",
    "بعد كل زفير، توقّف لحظة قصيرة؛ ففي هذه المساحة سكون عميق.",
    "اليقظة لا تعني إفراغ الذهن، بل مراقبته بلطف.",
    "كرّر في داخلك: أنا هادئ، أنا حاضر، وأنا كافٍ.",
    "وجّه انتباهك إلى الجسد كله، كأنه مجال حي من الإحساس.",
    "في نهاية الجلسة، خذ نفسًا عميقًا واحدًا، ثم عد إلى المكان بامتنان.",
)

internal val TIPS_DE = listOf(
    "Atme ruhig ein – vier Zählzeiten – und langsam aus – sechs Zählzeiten.",
    "Wenn dein Geist wandert, kehre sanft und ohne Urteil zum Atem zurück.",
    "Versuche nichts zu verändern – beobachte einfach, was ist.",
    "Spüre deinen Körper von innen: Füße, Beine, Bauch, Brust, Hände.",
    "Lass jeden Gedanken vorbeiziehen wie eine Wolke am Himmel.",
    "Richte deine Aufmerksamkeit auf den Moment zwischen Einatmen und Ausatmen.",
    "Wenn Geräusche auftauchen, nimm sie wahr – ohne sie zu bewerten.",
    "Du bist der Beobachter, nicht das Beobachtete.",
    "Mit jedem Ausatmen darfst du loslassen.",
    "Entspanne bewusst: Stirn, Kiefer, Schultern, Hände.",
    "Spüre die Berührungspunkte deines Körpers mit dem Boden oder dem Sitz.",
    "Stell dir vor, dein Herz atmet – sanft und rhythmisch.",
    "Ein leises inneres Lächeln entspannt den gesamten Körper.",
    "Dieser Moment ist vollständig. Ihm fehlt nichts.",
    "Zähle innerlich bis zehn Atemzüge, dann beginne von vorne.",
    "Beobachte, wo im Körper du den Atem am deutlichsten spürst.",
    "Metta: Wünsche dir selbst Wohlbefinden – «Möge ich glücklich sein.»",
    "Weite es aus: «Mögen alle Wesen glücklich und frei von Leid sein.»",
    "Bei Unruhe: atme bewusst tief in den Bauch – das beruhigt das Nervensystem.",
    "Stell dir deinen Geist als stillen See vor – Gedanken sind Wellen, die vergehen.",
    "Nach jedem Ausatmen: halte kurz inne – in dieser Pause liegt tiefe Stille.",
    "Achtsamkeit bedeutet nicht, den Geist zu leeren, sondern ihn freundlich zu beobachten.",
    "Wiederhole innerlich: «Ich bin ruhig. Ich bin hier. Ich bin genug.»",
    "Richte deine Aufmerksamkeit auf den Körper als Ganzes – als lebendiges Feld der Empfindungen.",
    "Am Ende jeder Sitzung: ein tiefer Atemzug – und kehre dankbar in den Raum zurück.",
)

internal val TIPS_EN = listOf(
    "Breathe in for four counts, then slowly out for six.",
    "When the mind wanders, gently return to the breath – without judgment.",
    "Try not to change anything – simply observe what is.",
    "Scan your body from within: feet, legs, belly, chest, hands.",
    "Let each thought pass like a cloud drifting across the sky.",
    "Rest your attention on the natural pause between inhale and exhale.",
    "When sounds arise, notice them – without labelling or judging.",
    "You are the observer, not the observed.",
    "With each exhale, allow yourself to let go a little more.",
    "Consciously soften: forehead, jaw, shoulders, hands.",
    "Feel the points where your body meets the floor or seat.",
    "Imagine your heart breathing – softly and rhythmically.",
    "A gentle inner smile relaxes the entire body.",
    "This moment is complete. Nothing is missing.",
    "Count ten breaths silently, then begin again from one.",
    "Notice where in the body you feel the breath most clearly.",
    "Metta: wish yourself well – «May I be happy. May I be at ease.»",
    "Expand it outward: «May all beings be happy and free from suffering.»",
    "With restlessness, breathe deeply into the belly – it calms the nervous system.",
    "Picture your mind as a still lake – thoughts are waves that arise and pass.",
    "After each exhale, pause briefly – in that gap lies deep stillness.",
    "Mindfulness doesn't mean emptying the mind, but observing it with kindness.",
    "Repeat inwardly: «I am calm. I am here. I am enough.»",
    "Bring attention to the body as a whole – a living field of sensation.",
    "At the end of the session, one deep breath – and return to the room with gratitude.",
)
